COMPILE=em++ -fPIC -Wall -O3 -std=c++17 -DNDEBUG
LINK=emar
all: libcadiback.a
libcadiback.a: cadiback.o ../cadical/build/libcadical.a makefile
	$(LINK) rcs $@ cadiback.o
cadiback.o: cadiback.cpp config.hpp ../cadical/src/cadical.hpp makefile
	$(COMPILE) -c $< -I../cadical/src
config.hpp: generate VERSION makefile
	./generate > $@
clean:
	rm -f cadiback.o config.hpp cadiback makefile test/*log test/*err

.PHONY: all clean format test
